export const CUSTOMER_PROFILE_FIELDS = [
  {
    name: 'name',
    label: 'Full Name',
    type: 'text',
    required: true,
    editable: true,
    section: 'personal',
  },
  {
    name: 'email',
    label: 'Email Address',
    type: 'email',
    required: true,
    editable: false,
    section: 'personal',
  },
  {
    name: 'phone',
    label: 'Phone Number',
    type: 'text',
    required: true,
    editable: true,
    section: 'personal',
  },
  {
    name: 'aadhaarNumber',
    label: 'Aadhaar Card Number',
    hasKey: 'hasAadhaar',
    type: 'text',
    required: false,
    editable: true,
    section: 'kyc',
    mask: (val) => val ? `XXXX XXXX ${val.slice(-4)}` : '',
    placeholder: '12 digit Aadhaar',
    maxLength: 12,
    validationPattern: /^\d{12}$/,
    validationMessage: 'Aadhaar must be exactly 12 digits',
  },
  {
    name: 'panNumber',
    label: 'PAN Card Number',
    hasKey: 'hasPan',
    type: 'text',
    required: false,
    editable: true,
    section: 'kyc',
    mask: (val) => val ? `XXXXXX${val.slice(-4)}` : '',
    placeholder: 'ABCDE1234F',
    validationPattern: /^[A-Z]{5}[0-9]{4}[A-Z]$/,
    validationMessage: 'PAN must be in format ABCDE1234F',
  },
  {
    name: 'dateOfBirth',
    label: 'Birth Date',
    hasKey: 'hasDateOfBirth',
    type: 'date',
    required: false,
    editable: true,
    section: 'kyc',
  },
];
